# -*- coding: utf-8 -*-
"""Montador_assembly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJdhIW0CyW5LFX5THgtfgw5rmC3x9uRl
"""

memory = 256 * ['00'] #Inicialização da memória com todos os seus espaços preenchidos com '00'
rs = {'R0': '00', 'R1': '01', 'R2': '10', 'R3': '11'}; tipo = {'ADDR': '1', 'DATA': '0'} #Dicionários para os registradores (rs) e os tipos possiveís das instruções input/output
jcaez = {'JZ': '0001', 'JE': '0010', 'JEZ': '0011', 'JA': '0100', 'JAZ': '0101', 'JAE': '0110', 'JAEZ': '0111', 'JC': '1000', 'JCZ': '1001', 'JCE': '1010', 'JCEZ': '1011', 'JCA': '1100', 'JCAZ': '1101', 'JCAE': '1110', 'JCAEZ': '1111'}
#Dicionário para os casos de jcaez

def number(n): #Função para transformar um valor em decimal ou binário para hexadecimal. Se ele estiver em hexadecimal, apenas retorna o valor na formatação padrão
  if n[:2] == '0B':
    return hex(int(n, 2))
  elif n[:2] == '0X':
    return hex(int(n, 16))
  else:
    n = int(n, 10)
    if n<0:
      n = (1 << 8) + n
    return hex(n)

def read_archive_asm(arquivo_entrada): #Função para ler o arquivo de entrada e criar uma lista de listas com o que foi lido para usar no montador
  with open(arquivo_entrada, 'r') as f:
    content = f.read()
  programa_asm = content.upper().split('\n') #Separa as linhas
  for i in range(len(programa_asm)): #Trata da formatação da lista de listas
    programa_asm[i] = programa_asm[i].replace(' ', ',').split(',')
    programa_asm[i] = list(filter(lambda a: a != '', programa_asm[i]))
  programa_asm = list(filter(lambda a: a != [], programa_asm))
  programa_asm = list(filter(lambda a: a[0][0] != ';', programa_asm))
  print(programa_asm)
  return programa_asm

def write_output(arquivo_saida): #Função que escreve o arquivo de saída
  with open(arquivo_saida, 'w') as f:
    f.write('v3.0 hex words plain\n')
    for i in range(len(memory)-1):
      f.write(memory[i] + '\n')
    f.write(memory[len(memory)-1])

def montador(): #O código do montador em si
  print("Executando como script principal.") #Indica que o programa começou
  asm = read_archive_asm('programa.asm') #Lê o arquivo de entrada
  i=0 #Indice das instruções assembly
  j=0 #Indice da memória
  while ((i<len(asm))and(i<255)):
    a="" #Usado para construir as instruções em binário
    match asm[i][0]:
      #Casos do formato RA,RB
      case 'LD':
        a+= '0000'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'ST':
        a+= '0001'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'ADD':
        a+= '1000'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'SHR':
        a+= '1001'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'SHL':
        a+= '1010'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'NOT':
        a+= '1011'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'AND':
        a+= '1100'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'OR':
        a+= '1101'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'XOR':
        a+= '1110'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'CMP':
        a+= '1111'
        a+= rs[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      #Casos de formatação diferente
      case 'IN':
        a+= '0111'
        a+= '0'
        a+= tipo[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'OUT':
        a+= '0111'
        a+= '1'
        a+= tipo[asm[i][1]]
        a+= rs[asm[i][2]]
        memory[j]= hex(int(a, 2))
      case 'DATA':
        a+='001000'
        a+= rs[asm[i][1]]
        memory[j]= hex(int(a, 2))
        j+=1; memory[j] = number(asm[i][2])
      case 'JMPR':
        a+= '001100'
        a+= rs[asm[i][1]]
        memory[j]= hex(int(a, 2))
      case 'JMP':
        a+= '01000000'
        memory[j]= hex(int(a, 2))
        j+=1
        memory[j]= number(asm[i][1])
      case 'CLF':
        a+= '01100000'
        memory[j]= hex(int(a, 2))
      case _: #Caso do jcaez
        a+= '0101'
        a+= jcaez[asm[i][0]]
        memory[j]= hex(int(a, 2))
        j+=1
        memory[j]= number(asm[i][1])
    i+=1
    j+=1
  write_output('exe3.txt') #Escreve o arquivo de saída

if __name__ == '__main__': #Main
  montador()